language: c
services: docker
os: linux

matrix:
  include:
    - os: linux
      arch: arm64
    - os: linux
      arch: arm64-graviton2
      dist: focal
      virt: lxd
      group: edge

install:
  - uname -m

notifications:
  email: false
